### ISSUE TITLE
Keep track of metadata better

### ISSUE THREAD

**Issue by tjlang** [nguy/AWOT#16]
AWOT appears to only ingest the data arrays, and not much metadata associated with each variable. I think it should try to use nested dictionaries like Py-ART to keep track of important metadata like units, full variable names, and other details. For example, instead of accessing the data like this:

`fl['latitude']`

You should access it like this:

`fl['latitude']['data']`

That way you could also get important info like `fl['latitude']['units']`, `fl['latitude']['full_name']`, etc.

The plotting routines could also take advantage of this when constructing default axis labels, titles, etc.

**Comment by nguy** [comment]
I agree, I've been thinking about this for some time. This is a legacy of being an initial construct for a specific dataset and not thinking ahead. I'll see about changing this after we work through PR #15 .

**Comment by nguy** [comment]
So just poking through the code and it appears I did retain metadata on the radar side, but not the flight data side for some odd reason. I think this will be a quick fix.

**Comment by nguy** [comment]
A few issues I didn't expect came up, mostly because I decided to update the netCDF reader. See PR #19
