### ISSUE TITLE
Merge T-28 reader and netCDF reader?

### ISSUE THREAD

**Issue by tjlang** [nguy/AWOT#17]
Now that #15 is merged, we should evaluate whether the T-28 reader and the general netCDF reader should ultimately be merged into a single routine. There are pros and cons to each approach, so I think a final decision will come from further experience with using AWOT. I am definitely open to #16 being addressed sooner than this, since this is a lower priority.

**Comment by nguy** [comment]
Agreed, I'm working on a quick update of netCDF reader that allows the user to specify the time dimension and hopefully handles the time more robustly. I was also going to see about pulling the metadata more robustly at the same time. Hopefully I can knock this out today and post later.

**Comment by nguy** [comment]
Okay, I was able to read T-28 data with the updated netCDF reader. The gotcha is that the `time_var` keyword **has** to be provided due to some logic issues. Maybe those can be cleaned up later.

**Comment by nguy** [comment]
Oh and one more thing, the turbulence conversion was not included. I wasn't sure if this should be part of a general reader.

**Comment by tjlang** [comment]
Cool, I'll try to check this out in the coming days. Yeah, if metadata are included then whatever units different stuff are in becomes less relevant.

**Comment by nguy** [comment]
Yeah, I didn't fully implement this into the plotting code. I'll need to comb through and see where mods can be made.

**Comment by nguy** [comment]
I also just pushed a t28 example file.
