### ISSUE TITLE
Discrete value color bar in awot_plot_wcr2.ipynb

### ISSUE THREAD

**Issue by cjjhnst2** [nguy/AWOT#27]
Hello,

Is there a way to change the color bars to have discrete values for the vertical reflectivity and vertical velocity flight leg plots?

I have attached both an example plot of vertical radial velocity (made with Matlab) that has a discrete color bar and the velocity color map I used to make the plot. 

Thank you.

<img width="1361" alt="vertical_radial_velocity_example" src="https://cloud.githubusercontent.com/assets/16808758/12467733/84272c42-bfa3-11e5-8360-bf78ea7dfd1c.png">

[vel_colortable.xlsx](https://github.com/nguy/AWOT/files/98470/vel_colortable.xlsx)

**Comment by nguy** [comment]
See the newest update. And refer to the WCR example for usage.

Let me know if you have any issues.
