### ISSUE TITLE
Add HIAPER radar reader

### ISSUE THREAD

**Issue by nguy** [nguy/AWOT#32]
[NCAR W-band HIAPER radar](https://www.eol.ucar.edu/observing_facilities/hiaper-gulfstream-gv)

**Comment by adlyons** [comment]
Can you link an example data file to work with here?

**Comment by adlyons** [comment]
Can you link an example data file to work with here?

**Comment by nguy** [comment]
I'll send one to you. It can be read with Py-ART, but some of the metadata is incorrect, specifically platform type is 'fixed' and should be something to do with aircraft. I've contacted NCAR and notified them. 

I don't think this data is used at this point, but we should keep it in mind for the future.

**Comment by nguy** [comment]
Addressed in PR #34
