### ISSUE TITLE
Replace Nappy

### ISSUE THREAD

**Issue by nguy** [nguy/AWOT#4]
While Nappy is a nice was to read in the NASA Ames format, it is cumbersome with it's dependencies and is not easily available. Another option is another package called NAStools, but it does not appear to be complete or maintained.

It will likely be easier in the long run to port the code to read NASA Ames format over to AWOT.
@tjlang @swnesbitt Do either of you know a python package other than those mentioned above that reads NASA Ames format (if you're familiar with this)?

**Comment by tjlang** [comment]
I would just write your own package to decode this format. It's essentially ASCII, right? Numpy may be the only dependency you need to read then. You may want to put it into a CF-compliant data model. Also write it to work with Python 3 out of the box. 

I'd use the xray data structures so you can write to netCDF with one line of code. I'll probably do that at some point with MMM-Py and PyAMPR.

**Comment by swnesbitt** [comment]
+1 to Tim’s proposal.

From: Nick
Reply-To: nguy/AWOT
Date: Wednesday, August 26, 2015 at 11:54 PM
To: nguy/AWOT
Cc: Steve Nesbitt
Subject: [AWOT] Replace Nappy (#4)

While Nappy is a nice was to read in the NASA Ames format, it is cumbersome with it's dependencies and is not easily available. Another option is another package called NAStools, but it does not appear to be complete or maintained.

It will likely be easier in the long run to port the code to read NASA Ames format over to AWOT.
@tjlanghttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tjlang&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=b78JitbnUtsnbMgSxSoEjYwC8jfDRuf4jC0q7nNk5HM&s=wZO1qvB4oDn5MImqY7uth7Wtpjpbutp3svjDZC517W8&e= @swnesbitthttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_swnesbitt&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=b78JitbnUtsnbMgSxSoEjYwC8jfDRuf4jC0q7nNk5HM&s=oPWu7PwBNn99ipfXC_LHnvOGZ3JyiKuG0rXhCWbgr3A&e= Do either of you know a python package other than those mentioned above that reads NASA Ames format (if you're familiar with this)?

**Comment by nguy** [comment]
That is what I've been leaning toward. 
I've been experimenting with xray. It's a nice tool thus far, hopefully it will continue to be more common place. It's a lot easier to work with than other CDM packages in my opinion. I'm also now 95% sure that AWOT is going to be converted to Pandas in the future. Just need to find the time to do this. 

I've not actually worked with any NASA aircraft data, if either of you have a file lying around, I'd be interested in seeing this.

**Comment by nguy** [comment]
With 2nd generation this was taken care of. No more dependency on this package. Internal reader for FFI 1001 now available. Other FFI (NASA Ames) formats could be added in the future.
