### ISSUE TITLE
WCR Plotting

### ISSUE THREAD

**Issue by cjjhnst2** [nguy/AWOT#42]
<img width="892" alt="screen shot 2016-10-08 at 12 55 23 am" src="https://cloud.githubusercontent.com/assets/16808758/19210779/58c64980-8cf2-11e6-97a3-cf1def0197ff.png">

Hello,

I am having an issue when plotting WCR cross sections with the fill_surface=True function of .time_height_image. The fill surface seems to be filling areas randomly above ground. I have tried rerunning my program, however, that does not help.

**Comment by nguy** [comment]
Did the masking method work that we talked about via email?
If so what values were throwing the reader off? We could institute some sort of max height, but not sure what to choose.

**Comment by cjjhnst2** [comment]
I will get back to you on this, I have not had time to look directly into this issue.
