### ISSUE TITLE
Masking statistical data

### ISSUE THREAD

**Issue by cjjhnst2** [nguy/AWOT#44]
For the statistical plots (mean/median/skewness/std. dev. of reflectivity and vertical velocity), is there a way to mask the heights on the statistical plot for each leg that is plotted (similar to what you just made for the fill cfads and quantiles methods)? When the statistics are calculated near the ground, the calculated mean/median/skewness/std. dev. reflectivity and vertical velocity increase substantially. I have attached an example image to show you what I mean.

![mean_reflectivity](https://cloud.githubusercontent.com/assets/16808758/19357598/fadfa876-9137-11e6-830a-5807ab71a58d.png)

**Comment by nguy** [comment]
Are you using the `plot_vp` method?
If so there are keywords _mask_above_height_, _mask_below_height_, and _mask_between_height_ that I think should work.

**Comment by cjjhnst2** [comment]
I am actually using the other method you have shown in awot_cfad_demo.ipynb:

figC, (ax1, ax2) = plt.subplots(1, 2, figsize=(20,10))

#-----
#Plot Mean Reflectivity Profiles For Legs 6-10

ax1.set_axis_bgcolor('white')
ax2.set_axis_bgcolor('white')

ax1.plot(vp_statwcrZ10['vp_mean'], vp_statwcrZ10['yaxis'], label='Leg 10', color='darkred')
ax1.hold(True)
ax1.plot(vp_statwcrZ9['vp_mean'], vp_statwcrZ9['yaxis'], label='Leg 9', color='darkorange')
ax1.hold(True)
ax1.plot(vp_statwcrZ8['vp_mean'], vp_statwcrZ8['yaxis'], label='Leg 8', color='darkgreen')
ax1.hold(True)
ax1.plot(vp_statwcrZ7['vp_mean'], vp_statwcrZ7['yaxis'], label='Leg 7', color='darkviolet')
ax1.hold(True)
ax1.plot(vp_statwcrZ6['vp_mean'], vp_statwcrZ6['yaxis'], label='Leg 6', color='darkblue')

ax1.set_xlabel(r'Reflectivity (dB${Z}$$_{e}$)', fontsize=16)
ax1.set_ylabel(r'Height above MSL (km)', fontsize=16)
ax1.set_title(r'Mean Reflectivity - Legs 6-10', fontsize=16, y=1.01)
ax1.legend(loc='best', shadow=True, fontsize=16)
ax1.tick_params(axis='x', labelsize=16, pad=10)
ax1.tick_params(axis='y', labelsize=16, pad=10)
ax1.axis([-30, 20, 0, altmax])

majorLocator = MultipleLocator(500)
majorFormatter = FormatStrFormatter('%d')
minorLocator = MultipleLocator(100)
ax1.yaxis.set_major_locator(majorLocator)
ax1.yaxis.set_major_formatter(majorFormatter)
ax1.yaxis.set_minor_locator(minorLocator)

majorLocator = MultipleLocator(5)
majorFormatter = FormatStrFormatter('%d')
minorLocator = MultipleLocator(1)
ax1.xaxis.set_major_locator(majorLocator)
ax1.xaxis.set_major_formatter(majorFormatter)
ax1.xaxis.set_minor_locator(minorLocator)

ax1.grid(True)
ax1.grid(color='k', linestyle=':', linewidth=0.5)
#-----

#-----
#Plot Mean Vertical Radial Velocity Profiles For All Legs

ax2.plot(vp_statwcrW10['vp_mean'], vp_statwcrW10['yaxis'], label='Leg 10', color='darkred')
ax2.hold(True)
ax2.plot(vp_statwcrW9['vp_mean'], vp_statwcrW9['yaxis'], label='Leg 9', color='darkorange')
ax2.hold(True)
ax2.plot(vp_statwcrW8['vp_mean'], vp_statwcrW8['yaxis'], label='Leg 8', color='darkgreen')
ax2.hold(True)
ax2.plot(vp_statwcrW7['vp_mean'], vp_statwcrW7['yaxis'], label='Leg 7', color='darkviolet')
ax2.hold(True)
ax2.plot(vp_statwcrW6['vp_mean'], vp_statwcrW6['yaxis'], label='Leg 6', color='darkblue')

ax2.set_xlabel(r'Vertical Radial Velocity (m s$^{-1}$)', fontsize=16)
ax2.set_ylabel(r'Height above MSL (km)', fontsize=16)
ax2.set_title(r'Mean Vertical Radial Velocity - Legs 6-10', fontsize=16, y=1.01)
ax2.legend(loc='best', shadow=True, fontsize=16)
ax2.tick_params(axis='x', labelsize=16, pad=10)
ax2.tick_params(axis='y', labelsize=16, pad=10)
ax2.axis([-2, 2, 0, altmax])

majorLocator = MultipleLocator(500)
majorFormatter = FormatStrFormatter('%d')
minorLocator = MultipleLocator(100)
ax2.yaxis.set_major_locator(majorLocator)
ax2.yaxis.set_major_formatter(majorFormatter)
ax2.yaxis.set_minor_locator(minorLocator)

majorLocator = MultipleLocator(1)
majorFormatter = FormatStrFormatter('%d')
minorLocator = MultipleLocator(0.2)
ax2.xaxis.set_major_locator(majorLocator)
ax2.xaxis.set_major_formatter(majorFormatter)
ax2.xaxis.set_minor_locator(minorLocator)

ax2.grid(True)
ax2.grid(color='k', linestyle=':', linewidth=0.5)
#-----

figC.tight_layout()

# Force change labels for x-axis

labels = [item.get_text() for item in ax1.get_yticklabels()]
labels[1] = '0'
labels[2] = '0.5'
labels[3] = '1.0'
labels[4] = '1.5'
labels[5] = '2.0'
labels[6] = '2.5'
ax1.set_yticklabels(labels)

# Force change labels for x-axis

labels = [item.get_text() for item in ax2.get_yticklabels()]
labels[1] = '0'
labels[2] = '0.5'
labels[3] = '1.0'
labels[4] = '1.5'
labels[5] = '2.0'
labels[6] = '2.5'
ax2.set_yticklabels(labels)

plt.savefig(savdir_stats + mean_z_w_legs_6_10, dpi=300, bbox_inches='tight', pad_inches=0.1)

I have attached my code as a .txt.

[statistics_thesis_script_iop1_dec07.txt](https://github.com/nguy/AWOT/files/527851/statistics_thesis_script_iop1_dec07.txt)

**Comment by nguy** [comment]
See the [relevant code](https://github.com/nguy/AWOT/blob/master/awot/graph/radar_utility.py#L798-L816) in plot_vp for how to mask the profiles.

**Comment by nguy** [comment]
PR #
