### ISSUE TITLE
Issue with qmask_above_height

### ISSUE THREAD

**Issue by cjjhnst2** [nguy/AWOT#45]
I am also having an issue with the qmask_above_height when plotting CFADs. I noticed that the data on both the reflectivity and vertical velocity CFADs are not masked correctly. I have specified that qmask_above_height = sfcleg7_maskabove, where sfcleg7_maskabove = 2470. For some reason, it is masking everything above 2370 m. This is for leg 7 in my code that I have attached. I have also attached the CFAD for leg 7 where this issue is occurring. Again I have attached my code as a .txt, so change the file name extension to .ipynb.

![cfad_leg7](https://cloud.githubusercontent.com/assets/16808758/19358139/66fffca2-913a-11e6-88ee-cb522bff7e21.png)

[CFAD_thesis_script_rf01_iop1_dec07.txt](https://github.com/nguy/AWOT/files/527703/CFAD_thesis_script_rf01_iop1_dec07.txt)

**Comment by nguy** [comment]
Just to verify where to look in the code are you trying to mask the CFAD distribution or the overlaid quantiles, or both?

**Comment by cjjhnst2** [comment]
I am trying to mask both the CFAD distribution and overlaid quantiles above 2470 m.

**Comment by nguy** [comment]
Okay, I just pushed some changes that should take care of this with a new _mask_above_height_, etc. keywords. These will be available upon merger with master branch.

**Comment by nguy** [comment]
If the latest merge works can you close the issue?

**Comment by nguy** [comment]
By the way, I just re-read this post. There was no CFAD masking previously, the _qmask_above_height_ only controls the quantiles masking. Which seems to be correct. The CFAD now has it's own masking keywords (remove the q to access).

**Comment by cjjhnst2** [comment]
I will try the latest merge this evening or tomorrow. Will let you know. Thank you!

**Comment by nguy** [comment]
PR #51 and PR #52
