### ISSUE TITLE
Possible change to track_height_image

### ISSUE THREAD

**Issue by cjjhnst2** [nguy/AWOT#46]
When using track_height_image, is there a way to convert the output on the x-axis to just be 0 km for start_time=s1 and whatever distance it is to end_time=e1 (say 25 km), instead of calculating the distance from the beginning of the netCDF file? Basically, is there a way to calculate the distance from start_time=s1 to end_time=e1? I have brute force changed the labels of the distance to say 0 at the beginning and X distance at the end depending on the end time for now.
# Force change labels for x-axis

labels = [item.get_text() for item in ax1.get_xticklabels()]
labels[0] = '0'
labels[1] = '5'
labels[2] = '10'
labels[3] = '15'
labels[4] = '20'
labels[5] = '25'
ax1.set_xticklabels(labels)
# Force change labels for x-axis

labels = [item.get_text() for item in ax2.get_xticklabels()]
labels[0] = '0'
labels[1] = '5'
labels[2] = '10'
labels[3] = '15'
labels[4] = '20'
labels[5] = '25'
ax2.set_xticklabels(labels)

**Comment by nguy** [comment]
I just pushed a small change that adds the _zero_track_start_ keyword. Try setting to True and see if it works.

**Comment by nguy** [comment]
PR #51
